name: CI
on:
    push:
      branches: [master]
    pull_request:
      branches: [master]
jobs:
    test:
      runs-on: ubuntu-latest

      services:
        mongodb:
          image: mongo:latest
          ports:
            - 27017:27017

        redis:
          image: redis:7-alpine
          ports:
            - 6379:6379
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - run: npm install

        - run: npm test
          env:
            MONGO_URI: mongodb://localhost:27017/ma_db_saas_test
            JWT_SECRET: test_secret_ci
            REDIS_URL: redis://localhost:6379
